app = 'todo-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = 'data'
  destination = '/data'

[env]
  PORT = '8080'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
